---
- name: check for already created ssh-key
  shell: ls -la /root/.ssh/id_rsa
  register: ssh_result
  ignore_errors: yes

- name: generate ssh-keys
  command: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -N ''
  when: ssh_result|failed

- name: make ssh directory in container
  command: mkdir -p {{ container }}/root/.ssh

- name: put ssh key into container for host access
  command: cp /root/.ssh/id_rsa.pub {{ container }}/root/.ssh/authorized_keys
